version: "2"
services:
  es:
    image: elasticsearch:2.3
  server:
    image: thelusina/foodtrucks-web
    command: python manage.py runserver
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  client:
    image: thelusina/cibuscart
    command: npm run start
    ports:
      - "3000:3000"
