version: "3"
services:
  es:
    restart: always
    image: elasticsearch:5.6.3

  server:
    restart: always
    command: python manage.py runserver
    build: ./server
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - es
    volumes:
      - .:/app

  client:
    restart: always
    build: ./client
    expose:
      - "3000"
    command: npm run start
    depends_on:
      - server
    ports:
      - "3000:3000"
