version: "3"
services:
  es:
    image: elasticsearch:2.3

  server:
    image: thelusina/cibuscart-server
    command: ./manage.py runserver
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  client:
    image: thelusina/cibuscart-client
    command: npm run start
    ports:
      - "3000:3000"
